### ISSUE TITLE
BIOS Settings

### ISSUE THREAD

**Issue by Flashminat0** [takina4655/EFI-for-HP-pavilion-gaming-16#1]
Can you please reply with bios settings you have changed ai do get a error bas follows
![IMG_20220104_113036](https://user-images.githubusercontent.com/64888128/148016002-b716f777-9ca3-4566-bd1e-521e563ed4c6.jpg)

**Comment by Flashminat0** [comment]
After disabling virtualization and secure boot I'm stuck on here 
![IMG_20220104_113720](https://user-images.githubusercontent.com/64888128/148016534-2092e30e-6eb5-4031-8a42-0462a4934f19.jpg)

**Comment by Askysoul** [comment]
donot disable virtualiuzation\

 btw this efi is not for initial boot
and did u modified the bios as i did 

if not then use ru efi and disable cfg lock

**Comment by Askysoul** [comment]
check the guide first 
how to disable bios cfg lock 
overclocking lock(optional)

**Comment by Flashminat0** [comment]
Thanks for the fast reply. Followed some guides and was able to flash the ru. But I need the offset to change the value of the cfg lock. Is there any way to find this.

**Comment by Flashminat0** [comment]
Ok found it as 0xE2

**Comment by Flashminat0** [comment]
![IMG_20220104_162439](https://user-images.githubusercontent.com/64888128/148049071-411414a7-21e1-44b0-9b3d-1886d858c532.jpg)


As you can see here it's already set to 0 ?

0xE2 means 

.              2

E.            X


Right?

**Comment by Flashminat0** [comment]
To find the address I need the firmware image. Where did you find it.

Or do you remember the address where should I change the 01 to 00 on here
![IMG_20220104_162439](https://user-images.githubusercontent.com/64888128/148051999-d4c0491b-a414-40c7-8f9d-861b5c1438f1.jpg)

**Comment by Askysoul** [comment]
bro pls dont do it without knowing

i went to the efi folder of the pc before installing macos in ssd and extracted the current bios and went with various steps like imma send u pics now watch yourself

and yeah pls make a new smbios becoz the current one is for my apple ac gonna hbe some trouble if not fixed now

**Comment by Flashminat0** [comment]
OK bro please. Thanks . I cant control myself using windows as im playing games. installing macos becuase then i can study hard. Thank you

**Comment by Flashminat0** [comment]
ok so i copied the EFI folder of C drive to another

![image](https://user-images.githubusercontent.com/64888128/148652004-87698174-0dfe-4734-8d13-7aeabe67d82d.png)

i Think this is what you are also refering to

**Comment by Askysoul** [comment]
[
![IMG_20211125_124305](https://user-images.githubusercontent.com/76640596/148651395-30cf271d-6204-47ca-97d4-04485cc417e9.jpg)
](url)
![IMG_20211125_124309](https://user-images.githubusercontent.com/76640596/148651406-0dd1add7-aefd-46f7-94d1-708afd3365d6.jpg)
![IMG_20211125_124312](https://user-images.githubusercontent.com/76640596/148651420-0c6dd49a-74f3-4299-a2db-3dc1c075acb8.jpg)
![IMG_20211126_033302](https://user-images.githubusercontent.com/76640596/148651430-0bbee7a3-0046-4a8f-a210-49b06a4f4879.jpg)
![IMG_20211126_034130](https://user-images.githubusercontent.com/76640596/148651442-b74bca3f-8f6c-4512-ab74-b28fb91f5e03.jpg)
![IMG_20211126_034132](https://user-images.githubusercontent.com/76640596/148651475-b73c0693-d581-4870-b515-2614c2b9ec5e.jpg)
![IMG_20211128_135130](https://user-images.githubusercontent.com/76640596/148651487-2f7e317b-dccc-46dc-9c41-d7e02cb3f12e.jpg)
![IMG_20211128_162029](https://user-images.githubusercontent.com/76640596/148651499-2f4339b3-c384-4878-b91f-eb09c6f5210a.jpg)
![IMG_20211128_171508](https://user-images.githubusercontent.com/76640596/148651505-18bee21b-5362-4b2c-b1df-b4499a53f6ad.jpg)
![IMG_20211128_171555](https://user-images.githubusercontent.com/76640596/148651516-1e1329fe-39ab-4a39-9543-278c198084c8.jpg)
![IMG_20211128_171558](https://user-images.githubusercontent.com/76640596/148651545-864dc07b-7ad5-4389-b5d9-fdd255f6dcc9.jpg)
![IMG_20211128_171713](https://user-images.githubusercontent.com/76640596/148651557-20d23c90-e4f1-4361-9da9-a00274ce6084.jpg)
![IMG_20211128_171716](https://user-images.githubusercontent.com/76640596/148651571-75d7ed9f-362b-4eaa-8ccd-21ab2e78bbb1.jpg)
![IMG_20211128_174001](https://user-images.githubusercontent.com/76640596/148651596-573819e3-dde7-4fac-a95e-9de9b987a8b8.jpg)
![IMG_20211128_174007](https://user-images.githubusercontent.com/76640596/148651602-42a571b6-0c0b-48ee-af60-04c0877c34dd.jpg)
![IMG_20211128_174013](https://user-images.githubusercontent.com/76640596/148651610-af6ee9ca-1746-4b1b-ae9c-d0784319fac7.jpg)
![IMG_20211128_174018](https://user-images.githubusercontent.com/76640596/148651624-37b365e9-82ff-488a-93fd-a44ea2b18921.jpg)
![IMG_20211128_174022](https://user-images.githubusercontent.com/76640596/148651635-8933a922-2d66-42a3-ad29-383caa9ece61.jpg)
![IMG_20211128_175744](https://user-images.githubusercontent.com/76640596/148651641-1867c7f4-0937-4751-bbda-bcd6e6d74e7a.jpg)
![IMG_20211128_184739](https://user-images.githubusercontent.com/76640596/148651647-0222616d-2a57-4636-8550-c05f8ed63b43.jpg)
![IMG_20211128_184741](https://user-images.githubusercontent.com/76640596/148651651-274ce62b-7ead-4b88-98fb-901837b17d30.jpg)
![IMG_20211128_210304](https://user-images.githubusercontent.com/76640596/148651655-7dbe1709-b0c1-4077-b783-ef26c4a0a8e2.jpg)
![IMG_20211128_211829](https://user-images.githubusercontent.com/76640596/148651664-de655e44-c19b-426a-a1ae-9466f1ed4ff6.jpg)
![IMG_20211128_211833](https://user-images.githubusercontent.com/76640596/148651670-56c48778-3e3b-4a85-b367-f4719084f6c2.jpg)
![IMG_20211128_223413](https://user-images.githubusercontent.com/76640596/148651676-417dd158-739f-4abe-8fb0-f0bf87f03d94.jpg)
![IMG_20211128_223426](https://user-images.githubusercontent.com/76640596/148651682-f2928a64-7ce4-4bb1-a6ea-480d283f6ef7.jpg)
![IMG_20211128_223448](https://user-images.githubusercontent.com/76640596/148651687-568aa7b4-8a14-49db-b8fb-582dbd2810e1.jpg)
![IMG_20211128_234918](https://user-images.githubusercontent.com/76640596/148651696-f532e970-5935-4bbd-a4f0-08e17163bb11.jpg)
![IMG_20211128_234957](https://user-images.githubusercontent.com/76640596/148651702-5f248797-dcf8-4e47-b677-abf092949fba.jpg)

**Comment by Askysoul** [comment]
> ok so i copied the EFI folder of C drive to another
> 
> ![image](https://user-images.githubusercontent.com/64888128/148652004-87698174-0dfe-4734-8d13-7aeabe67d82d.png)
> 
> i Think this is what you are also refering to

i hbe uploaded all the pics


> ok so i copied the EFI folder of C drive to another
> 
> ![image](https://user-images.githubusercontent.com/64888128/148652004-87698174-0dfe-4734-8d13-7aeabe67d82d.png)
> 
> i Think this is what you are also refering to

yea thats it now take that file go into ur macos and open it in uefi extractor

**Comment by Askysoul** [comment]
btw dont even try to use the value thst i highlighted because mine is i5 with ami f.22 and with my custom config

**Comment by Askysoul** [comment]
take the bin file

**Comment by Flashminat0** [comment]
Bro thanks man I finally figured it out to do it and managed to unlock it. It shows as unlocked in that msre2 thing. But I still get the error.


![IMG_20220109_001900](https://user-images.githubusercontent.com/64888128/148656025-6b092eac-92c1-467f-be77-7d4613eb84c0.jpg)

**Comment by Flashminat0** [comment]
Do I need to change something because this is my first boot

**Comment by Askysoul** [comment]
yea ur efi is not working

**Comment by Flashminat0** [comment]
so i have to make efi from scratch right 😢

**Comment by Askysoul** [comment]
> 

sry bro for late reply but u dont need a new efi just change the config.plist to initial efi from guide nd u r done

i can do it for u but yea idk abt ur system bios and other things uk

**Comment by Flashminat0** [comment]
ok i get it . i did followed the guide. is there any specific settings to change I changed it using gensmbios. what are other things to change bro

**Comment by Askysoul** [comment]
ok so u do as u got in guide then oc clean snapshot my files from the efi and say the results

**Comment by Flashminat0** [comment]
ok bro ill oc clean spanshot and do as the guide says and tell u the results.

Do i need to do the ACPIs because I only managed to make 4 of them as the guide says but your efi has  more than it . am i missing something. 

CPU -> Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
and that is Comet Lake right so guide does not has that much ACPIs to go with 

please tell me if im doing somehing wrong

**Comment by Askysoul** [comment]
hmm u can take ur own acpi that would be better for ur system and yea the usb map.kext thats is my own configuration from utb tool so u can make it urs also using the tool and can get working sd card and mic and for bios settings u hbe taken ur own config so no prblm nd ur good to go bst of luck dude

**Comment by Flashminat0** [comment]
Thank bro I will try my best ❤️
