### ISSUE TITLE
Card reader & mic....

### ISSUE THREAD

**Issue by gnpaone** [takina4655/EFI-for-HP-pavilion-gaming-16#2]
Is your card reader working? What card reader you have (check in Windows device manager if you don't know)? What kext did you use if it worked in mac? Also, is the mic working for you? If yes, what applealc audio codec you are using?

**Comment by Flashminat0** [comment]
Did you manage to boot?

**Comment by gnpaone** [comment]
Ye, of course. Your efi is working well

**Comment by gnpaone** [comment]
> Did you manage to boot? 

Yes, of course. The efi is working well

**Comment by Flashminat0** [comment]
What settings you've changed in the BIOS. 

or did you disabled the cfg lock ?

**Comment by Askysoul** [comment]
bro sorry but i dont use the genesys card reader

**Comment by Askysoul** [comment]
is cam and bt working


yea i hbe disabled cfg lock before modifying the efi

**Comment by Askysoul** [comment]
i use the bt as the mic so iyts working ald the apple alc is mentioned in the readme file

**Comment by Flashminat0** [comment]
> yea i hbe disabled cfg lock before modifying the efi


whats the adress to unlock the cfg bro. cant find it

**Comment by Flashminat0** [comment]
can you provide the motherbord bios .bin file pls

**Comment by gnpaone** [comment]
> is cam and bt working

Yes, everything is working except mic and card reader

**Comment by gnpaone** [comment]
> can you provide the motherbord bios .bin file pls

I actually use i7 version of this laptop and I didn't modify anything in the provided efi except for a few cosmetic changes that doesn't affect any core settings. My bios version is f.10 which is latest for my laptop, and I changed nothing except disabling secure boot. I initially faced with booting the efi file if it is in the EFI internal disk so used USB disk initially, but now changed LauncherOption to Full and EFI is in internal disk and booting perfectly

**Comment by gnpaone** [comment]
I know i5 version too, just cpu difference, nothing else, by the way I removed -v (verbose mode) from boot arguments as that boot argument is well known for causing boot issues for various laptops. Btw thanks for the EFI ☺️

**Comment by Flashminat0** [comment]
what i get is a Apple IONVMEFAMILY error on the boot im helpless

**Comment by gnpaone** [comment]
> I know i5 version too, just cpu difference, nothing else, by the way I removed -v (verbose mode) from boot arguments as that boot argument is well known for causing boot issues for various laptops. Btw thanks for the EFI ☺️

So any help u can ask me 😉

**Comment by gnpaone** [comment]
> what i get is a Apple IONVMEFAMILY error on the boot im helpless

Ohh, did you modify the given EFI? Or can you share your EFI, and pic please? Also, where r u trying to install the mac - nvme SSD or sata SSD/HDD? Make sure the sata configuration is in AHCI in BIOS

**Comment by Askysoul** [comment]
> I know i5 version too, just cpu difference, nothing else, by the way I removed -v (verbose mode) from boot arguments as that boot argument is well known for causing boot issues for various laptops. Btw thanks for the EFI ☺️

hope u like it anyway is extrenal monitor working

**Comment by Askysoul** [comment]
btw all devices are working right

**Comment by gnpaone** [comment]
> > I know i5 version too, just cpu difference, nothing else, by the way I removed -v (verbose mode) from boot arguments as that boot argument is well known for causing boot issues for various laptops. Btw thanks for the EFI ☺️
> 
> hope u like it anyway is extrenal monitor working

External monitor won't work due to hdmi port tied up with nvidia GPU and clearly that GPU is not supported in mac so no way it will work

**Comment by gnpaone** [comment]
> btw all devices are working right

Yes, all the remaining devices working fine

**Comment by Askysoul** [comment]
> > is cam and bt working
> 
> Yes, everything is working except mic and card reader

ah i see

hmm i need to boot to mac os for fixing them but imma in windows  :/

**Comment by Askysoul** [comment]
> > > I know i5 version too, just cpu difference, nothing else, by the way I removed -v (verbose mode) from boot arguments as that boot argument is well known for causing boot issues for various laptops. Btw thanks for the EFI ☺️
> > 
> > 
> > hope u like it anyway is extrenal monitor working
> 
> External monitor won't work due to hdmi port tied up with nvidia GPU and clearly that GPU is not supported in mac so no way it will work

mm

**Comment by gnpaone** [comment]
> > what i get is a Apple IONVMEFAMILY error on the boot im helpless
> 
> Ohh, did you modify the given EFI? Or can you share your EFI, and pic please? Also, where r u trying to install the mac - nvme SSD or sata SSD/HDD? Make sure the sata configuration is in AHCI in BIOS

Pic please @Flashminat0 ? Also the vendor & model of SSD?

**Comment by Askysoul** [comment]
my model is from NVMe____KXG60ZNV256G_KIO4
