### ISSUE TITLE
CFG Locked

### ISSUE THREAD

**Issue by CodeBreakerSI** [takina4655/EFI-for-HP-pavilion-gaming-16#3]
How do I get rid of cfg locked?

**Comment by Askysoul** [comment]
? u mean unlock

**Comment by Flashminat0** [comment]
> ? u mean unlock

Yea bro please give guide

**Comment by stalo-01** [comment]
> > ? u mean unlock
> 
> Yea bro please give guide

ahh its a hard one you need ru.efi and dump the bios then find the lock and disable it also bios f.22 with you need your own smbios remember that

**Comment by Askysoul** [comment]
> > ? u mean unlock
> 
> Yea bro please give guide

so yea you can also use it with cfg lock i edited the files just now (~~)
