### ISSUE TITLE
Apple charge until the middle

### ISSUE THREAD

**Issue by Alscope14** [takina4655/EFI-for-HP-pavilion-gaming-16#4]
Hello thanks for your help with this laptop, I have a similar laptop with this specs:

CPU:i5 - 10300h
GPU:RTX-2060

Also is HP, the full code is hp pavilion gaming dk1040la and I was searching a lot for an EFI for this laptop and I found your share, but when I try to boot I got this screen
![image](https://user-images.githubusercontent.com/117844710/200969738-463f5629-611d-4ff0-95df-d08eb81016cb.jpeg)

And then and then the open core menu appears and I select the recovery option to install Monterey and the Apple logo appears and it loads up to the middle of the bar and there it stays bugged, I wanted to know if you could help me with this problem or if you know what is happening I am new to this topic and I need the computer to be able to program a project in IOS with xcode.
![image](https://user-images.githubusercontent.com/117844710/200970265-feeb2ff1-d4a3-443e-928b-744697b05417.jpeg)

I hope you can help me thank you very much! I'll send you a huge!

**Comment by stalo-01** [comment]
hrmm for this maybe the bios version is diffrent when i booted this in 2021 which i last booted btw then i unlocked my bios to get it installed also edited the codes with ru.efi in f.22 version but after that i never tried to boot it as i got some important files and yea it would be a mess to redo all and for the issue without log i cant do much maybe its the cfg lock or smth along those lines

**Comment by stalo-01** [comment]
> Hello thanks for your help with this laptop, I have a similar laptop with this specs:
> 
> CPU:i5 - 10300h GPU:RTX-2060
> 
> Also is HP, the full code is hp pavilion gaming dk1040la and I was searching a lot for an EFI for this laptop and I found your share, but when I try to boot I got this screen ![image](https://user-images.githubusercontent.com/117844710/200969738-463f5629-611d-4ff0-95df-d08eb81016cb.jpeg)
> 
> And then and then the open core menu appears and I select the recovery option to install Monterey and the Apple logo appears and it loads up to the middle of the bar and there it stays bugged, I wanted to know if you could help me with this problem or if you know what is happening I am new to this topic and I need the computer to be able to program a project in IOS with xcode. ![image](https://user-images.githubusercontent.com/117844710/200970265-feeb2ff1-d4a3-443e-928b-744697b05417.jpeg)
> 
> I hope you can help me thank you very much! I'll send you a huge!

check the last comment

**Comment by stalo-01** [comment]
it has various errors u provided the smbios right because i removed it maybe thats the issue so yea u need to add smbios to boot it properly

u need bios

**Comment by Askysoul** [comment]
> Hello thanks for your help with this laptop, I have a similar laptop with this specs:
> 
> CPU:i5 - 10300h GPU:RTX-2060
> 
> Also is HP, the full code is hp pavilion gaming dk1040la and I was searching a lot for an EFI for this laptop and I found your share, but when I try to boot I got this screen ![image](https://user-images.githubusercontent.com/117844710/200969738-463f5629-611d-4ff0-95df-d08eb81016cb.jpeg)
> 
> And then and then the open core menu appears and I select the recovery option to install Monterey and the Apple logo appears and it loads up to the middle of the bar and there it stays bugged, I wanted to know if you could help me with this problem or if you know what is happening I am new to this topic and I need the computer to be able to program a project in IOS with xcode. ![image](https://user-images.githubusercontent.com/117844710/200970265-feeb2ff1-d4a3-443e-928b-744697b05417.jpeg)
> 
> I hope you can help me thank you very much! I'll send you a huge!

hey sorry for the late reply but you need smbios and edit the plist as needed(it should be fixed in latest update)
