### ISSUE TITLE
Does not load to installer

### ISSUE THREAD

**Issue by Flashminat0** [takina4655/EFI-for-HP-pavilion-gaming-16#6]
![WhatsApp Image 2023-01-28 at 15 39 37](https://user-images.githubusercontent.com/64888128/215260759-e0151bf9-9472-422b-868f-0d4bbad5e007.jpg)

**Comment by Flashminat0** [comment]
![WhatsApp Image 2023-01-28 at 15 41 29](https://user-images.githubusercontent.com/64888128/215260812-5bbcfaad-b6a6-4c30-aef4-6db35bab0a43.jpg)
![WhatsApp Image 2023-01-28 at 15 41 28](https://user-images.githubusercontent.com/64888128/215260817-b990bdb4-ee88-4b47-90dd-fceafc472408.jpg)

**Comment by Askysoul** [comment]
did you did a clean snapshot and tried ?also did you used the release or directly from the repo
