### ISSUE TITLE
USB 3.0-3.2

### ISSUE THREAD

**Issue by groger34** [takina4655/EFI-for-HP-pavilion-gaming-16#7]
Hi!
     Great job, saved a lot of time. 
     Do USB ports work correctly with such a pair USBToolBox, UTBMap at your config as 3.0-3.2 , the mapping was made under Win or macOS and what does Hackintool show at the USB section ?

**Comment by yasas-mintpay** [comment]
Did you manage to boot into this EFI ?

**Comment by groger34** [comment]
Yes, w/o any problems. That Laptop is one of the best for . EFI 100% working

**Comment by Askysoul** [comment]
usb 3.1 and usb c port if you need more use utb toolbox for finding port use in windows for better search

**Comment by groger34** [comment]
Already done. Big thanks !

**Comment by Askysoul** [comment]
np welcome
