### ISSUE TITLE
Works Fine for macOS ventura but after sonoma upgrade broke

### ISSUE THREAD

**Issue by arielegs** [takina4655/EFI-for-HP-pavilion-gaming-16#8]
I know this is made to be for ventura but i wanted to request if you can make one for sonoma.
After the upgrade the display stays black for 30secs, No battery detected, Speakers not working(Found a fix after 2 hours)

I have the same hardware as you do.

**Comment by Askysoul** [comment]
not meant for sonoma 

currently updating to mac os 15

**Comment by Askysoul** [comment]
added sonoma soon 15
